spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update

uipath.robot.path=C:/Program Files/UiPathPlatform/Studio/26.0.192-cloud.22823/UiRobot.exe
uipath.project.biller=C:/Users/Admin/TransFlow_Bots/Dispatcher_GenerateInvoices.1.0.4.nupkg
uipath.project.collector=C:/Users/Admin/TransFlow_Bots/Client_Simulator.1.0.4.nupkg
uipath.project.auditor=C:/Users/Admin/TransFlow_Bots/Auditor_VerifyInvoices.1.0.5.nupkg